### ISSUE TITLE
Is this in active development?

### ISSUE THREAD

**Issue by prscX** [bamlab/native-navigation#8]
Hi @Almouro,

I am planning to migrate navigation to Airbnb/native-navigation but I don't think that is in active development. Due to their internal priorities they have kept development on hold

Is this fork in active development? Are you using it in production?

I am looking to use this fork for my app, is it feasible to use the same?

Thanks
Pranav

**Comment by Almouro** [comment]
Hi @prscX,

This fork is indeed in active development, but on the branch `bam`. Since `Airbnb/native-navigation` is not in active development, there is no need now to keep a separate branch, so I'm going to merge into master if @tychota agrees also.

We are indeed using it in production for one of our clients (with millions of users 🎉 ), to insert some React Native screens and components inside native apps.

**Comment by Almouro** [comment]
@prscX we publish it under `@bam.tech/native-navigation` btw, meaning you can do `yarn add  @bam.tech/native-navigation`

**Comment by prscX** [comment]
Thanks @Almouro for publishing it

I truly believe that Airbnb Native Navigation is very well architected and has great potential to become a single best solution for RN Navigation. I would be very happy to contribute from my end

Are you planning to use this in your other projects as well or planning to migrate to other Navigation solutions available in market such as (Wix:React-Native-Navigation/React-Navigation)

If you are planning to use this, do you have any plans for its future?

Thanks
Pranav

**Comment by Almouro** [comment]
Hi @prscX,

We use react-navigation in most of our projects at BAM, which are fully JS projects.
We'll probably use `native-navigation` in more projects for our current client, though. 

As far as I know, `react-native-navigation` does not have a adequate API to push screens or components from the native side, so it's not really fitting our needs.

**Comment by prscX** [comment]
Thanks @Almouro for the response, Good to hear that you are planning to using `native-navigation` in more projects

At MetricStream we are planning to use this folk in our mobile apps. Going forward we would love to contribute based on roadmap you decide

Thanks
Pranav
